awsl

diff --git a/package/lean/ezwifibroadcast/files/ezwifibroadcast.init b/package/lean/ezwifibroadcast/files/ezwifibroadcast.init
--- a/package/lean/ezwifibroadcast/files/ezwifibroadcast.init
+++ b/package/lean/ezwifibroadcast/files/ezwifibroadcast.init
@@ -29,18 +29,18 @@ function init_nic {
 	FREQ=$(uci get wbc.nic.freq)
 	CHANBW=$(uci get wbc.nic.chanbw)
 	PHY_NAME=$(iwinfo $NIC info|grep "PHY name"|cut -d ':' -f 3)
-	iw reg set CN					|| { echo "Init_NIC: Set Reg to CN failed!" && sleep 864000}
-	ifconfig $NIC mtu 2304 			|| { echo "Init_NIC: Set $NIC MTU failed!" && sleep 864000}
-	ifconfig $NIC down 				|| { echo "Init_NIC: Bringing down interface $NIC failed!" && sleep 864000}
-	iw dev $NIC set monitor none	|| { echo "Init_NIC: Set $NIC Monitor mode failed!" && sleep 864000}
-	ifconfig $NIC up 				|| { echo "Init_NIC: Bringing up interface $NIC failed!" && sleep 864000}
-	iw dev $NIC set freq $FREQ		|| { echo "Init_NIC: Set freq $FREQ MHz on $NIC failed!" && sleep 864000}
+	iw reg set CN					|| { echo "EZ-WifiBroadcast: Init_NIC: Set Reg to CN failed!" && sleep 864000}
+	ifconfig $NIC mtu 2304 			|| { echo "EZ-WifiBroadcast: Init_NIC: Set $NIC MTU failed!" && sleep 864000}
+	ifconfig $NIC down 				|| { echo "EZ-WifiBroadcast: Init_NIC: Bringing down interface $NIC failed!" && sleep 864000}
+	iw dev $NIC set monitor none	|| { echo "EZ-WifiBroadcast: Init_NIC: Set $NIC Monitor mode failed!" && sleep 864000}
+	ifconfig $NIC up 				|| { echo "EZ-WifiBroadcast: Init_NIC: Bringing up interface $NIC failed!" && sleep 864000}
+	iw dev $NIC set freq $FREQ		|| { echo "EZ-WifiBroadcast: Init_NIC: Set freq $FREQ MHz on $NIC failed!" && sleep 864000}
 	CHANBW_PATH=$(find /sys/kernel/debug/ieee80211 -name chanbw |grep $PHY_NAME)
 	if [ -f $(CHANBW_PATH) ]; then
-		echo "Init_NIC: $NIC maybe supports 5MHz/10MHz bandwidth."
+		echo "EZ-WifiBroadcast: Init_NIC: $NIC maybe supports 5MHz/10MHz bandwidth."
 		echo $(CHANBW) > $(CHANBW_PATH) 
 	else
-		echo "Init_NIC: $NIC on 5MHz/10MHz bandwidth is not supported. Use default instead."
+		echo "EZ-WifiBroadcast: Init_NIC: $NIC on 5MHz/10MHz bandwidth is not supported. Use default instead."
 	fi
 }
 
@@ -50,7 +50,7 @@ start_service() {
 	[ $(uci get wbc.wbc.enable) -eq 0 ] && exit
 	
 	# 0. Init Wi-Fi card here
-	echo "Init Wi-Fi Card..."
+	echo "EZ-WifiBroadcast: Init Wi-Fi Card..."
 	init_nic
 	echo $(measure) > /tmp/bitrate_measured_kbit
 	# To-do: Find out what these things mean and how to bypass
@@ -58,13 +58,14 @@ start_service() {
 	echo "0" > /tmp/cts
 	echo "0" > /tmp/undervolt 	# a wireless router should never...
 	
-	if [ "$(uci get wbc.wbc.mode)" = "tx" ]; then
-		echo "EZWifiBroadcast: TX mode enabled (Air)."
-		/usr/sbin/sharedmem_init_tx
-		
-		# 1. TX_RAWSOCK Instance
-		# Listen UDP on listen_port -> air
-		if [ $(uci get wbc.video.enable) -eq 1 ]; then
+	/usr/sbin/sharedmem_init_tx
+	/usr/sbin/sharedmem_init_rx
+	
+	# 1. Video TX/RX Instance
+	if [ $(uci get wbc.video.enable) -eq 1 ]; then
+		echo "EZ-WifiBroadcast: Video Transfer Enabled."
+		if [ "$(uci get wbc.video.mode)" = "tx" ]; then
+			# TX: Listen UDP on listen_port -> air
 			procd_open_instance "wbc_tx_rawsock"
 			procd_set_param stdout 1
 			procd_set_param stderr 1
@@ -80,78 +81,10 @@ start_service() {
 			procd_set_param pidfile /var/run/wbc/tx_rawsock.pid	
 			procd_set_param respawn ${respawn_threshold:-86400} ${respawn_timeout:-1} ${respawn_retry:-100}
 			procd_close_instance
-			echo "EZWifiBroadcast: Starting tx_rawsock..."
-		else
-			echo "EZWifiBroadcast: Video TX Disabled."
+			echo "EZ-WifiBroadcast: Video TX Mode, Starting tx_rawsock..."
 		fi
-		
-		# 2. RSSI TX Instance
-		if [ $(uci get wbc.rssi.enable) -eq 1 ]; then
-			procd_open_instance "wbc_rssitx"
-			procd_set_param stdout 1
-			procd_set_param stderr 1
-			procd_set_param command /usr/sbin/rssitx
-			procd_append_param command $(uci get wbc.nic.iface)
-			procd_set_param pidfile /var/run/wbc/rssitx.pid
-			procd_set_param respawn ${respawn_threshold:-86400} ${respawn_timeout:-1} ${respawn_retry:-100}
-			procd_close_instance
-			echo "EZWifiBroadcast: Starting rssitx..."
-		else
-			echo "EZWifiBroadcast: RSSI TX Disabled."
-		fi
-		
-		# 3. OSD TX Instance (Telemetry)
-		# wbc.telemetry.uart -> air
-		if [ $(uci get wbc.telemetry.enable) -eq 1 ]; then
-			echo "EZWifiBroadcast: Telemetry enabled on $(uci get wbc.telemetry.uart)."
-			stty -F $(uci get wbc.telemetry.uart) $(STTY_ARGS) $(uci get wbc.telemetry.baud)  
-			procd_open_instance "wbc_tx_telemetry"
-			procd_set_param stdout 1
-			procd_set_param stderr 1
-			procd_set_param command /usr/sbin/tx_telemetry \
-				-p $(uci get wbc.telemetry.port) \
-				-c $(uci get wbc.telemetry.cts) \
-				-r $(uci get wbc.telemetry.retrans) \
-				-x $(uci get wbc.telemetry.proto) \
-				-d $(uci get wbc.telemetry.bitrate) \
-				-y 0 $(uci get wbc.nic.iface)
-			procd_set_param pidfile /var/run/wbc/tx_telemetry.pid
-			procd_set_param respawn ${respawn_threshold:-86400} ${respawn_timeout:-1} ${respawn_retry:-100}
-			procd_close_instance
-			echo "EZWifiBroadcast: Starting Telemetry..."
-		else
-			echo "EZWifiBroadcast: Telemetry disabled."
-		fi
-
-		# 4. Uplink RX Instance
-		# air -> wbc.uplink.uart 
-		if [ $(uci get wbc.uplink.uplink_enable) -eq 1 ]; then
-			echo "EZWifiBroadcast: Uplink enabled on $(uci get wbc.uplink.uart)."
-			procd_open_instance "wbc_rx_rc_telemetry"
-			procd_set_param stdout 1
-			procd_set_param stderr 1
-			procd_set_param command /usr/sbin/rx_rc_telemetry \
-				-p $(uci get wbc.uplink.port) \
-				-r 99 \
-				-b $(uci get wbc.uplink.baud) \
-				-o 0 \
-				-s $(uci get wbc.uplink.uart) \
-				$(uci get wbc.nic.iface)
-			procd_set_param pidfile /var/run/wbc/rx_rc_telemetry.pid
-			procd_set_param respawn ${respawn_threshold:-86400} ${respawn_timeout:-1} ${respawn_retry:-100}
-			procd_close_instance
-			echo "EZWifiBroadcast: Starting Uplink RX..."
-		else
-			echo "EZWifiBroadcast: Uplink disabled."
-		fi
-	
-	else # RX	
-		echo "EZWifiBroadcast: RX mode enabled (Ground)."
-		/root/wifibroadcast/sharedmem_init_rx
-		
-		# 1. RX Instance
-		# Video stream received from air -> send_ip:send_port (UDP)
-		if [ $(uci get wbc.video.enable) -eq 1 ]; then
+		if [ "$(uci get wbc.video.mode)" = "rx" ]; then
+			# RX: Video stream received from air -> send_ip:send_port (UDP)
 			procd_open_instance "wbc_rx"
 			procd_set_param stdout 1
 			procd_set_param stderr 1
@@ -168,22 +101,20 @@ start_service() {
 			procd_set_param pidfile /var/run/wbc/rx.pid	
 			procd_set_param respawn ${respawn_threshold:-86400} ${respawn_timeout:-1} ${respawn_retry:-100}
 			procd_close_instance
-			echo "EZWifiBroadcast: Starting rx..."
-		else
-			echo "EZWifiBroadcast: Video RX Disabled."
+			echo "EZ-WifiBroadcast: Video RX Mode, Starting rx..."
 		fi
-		
-		# 2. OSD RX Instance (Telemetry)
-		# Maybe have bugs
+	fi
+	
+	# 2. OSD RX Instance (Telemetry) (Maybe have bugs)
+	if [ $(uci get wbc.telemetry.enable) -eq 1 ]; then
+		echo "EZ-WifiBroadcast: Telemetry Enabled."
 		# RX Telemetry received from air -> send_ip:send_port (UDP)
-		if [ $(uci get wbc.telemetry.enable) -eq 1 ]; then
-			echo "EZWifiBroadcast: Telemetry enabled, redirect to $(wbc.telemetry.send_ip_port)."
+		if [ "$(uci get wbc.telemetry.mode)" = "rx" ]; then
 			stty -F $(uci get wbc.telemetry.uart) $(STTY_ARGS) $(uci get wbc.telemetry.baud)  
 			procd_open_instance "wbc_rx_rc_telemetry_buf"
 			procd_set_param stdout 1
 			procd_set_param stderr 1
-			# rx_rc_telemetry_buf does not support rc
-			# so using /dev/null now
+			# rx_rc_telemetry_buf does not support rc so using /dev/null now
 			procd_set_param command /usr/sbin/rx_rc_telemetry_buf \
 				-p $(uci get wbc.telemetry.port) \
 				-b 19200 -s /dev/null -o 1 -r 0\
@@ -193,15 +124,54 @@ start_service() {
 			procd_set_param pidfile /var/run/wbc/rx_rc_telemetry_buf.pid
 			procd_set_param respawn ${respawn_threshold:-86400} ${respawn_timeout:-1} ${respawn_retry:-100}
 			procd_close_instance
-			echo "EZWifiBroadcast: Starting Telemetry..."
-		else
-			echo "EZWifiBroadcast: Telemetry disabled."
+			echo "EZ-WifiBroadcast: Telemetry RX Mode, Starting Telemetry..."
+			echo "EZ-WifiBroadcast: Telemetry redirect to $(wbc.telemetry.send_ip_port)."
 		fi
-		
-		# 3. Uplink TX Instance
+		# wbc.telemetry.uart -> air
+		if [ "$(uci get wbc.telemetry.mode)" = "tx" ]; then
+			stty -F $(uci get wbc.telemetry.uart) $(STTY_ARGS) $(uci get wbc.telemetry.baud)  
+			procd_open_instance "wbc_tx_telemetry"
+			procd_set_param stdout 1
+			procd_set_param stderr 1
+			procd_set_param command /usr/sbin/tx_telemetry \
+				-p $(uci get wbc.telemetry.port) \
+				-c $(uci get wbc.telemetry.cts) \
+				-r $(uci get wbc.telemetry.retrans) \
+				-x $(uci get wbc.telemetry.proto) \
+				-d $(uci get wbc.telemetry.bitrate) \
+				-y 0 $(uci get wbc.nic.iface)
+			procd_set_param pidfile /var/run/wbc/tx_telemetry.pid
+			procd_set_param respawn ${respawn_threshold:-86400} ${respawn_timeout:-1} ${respawn_retry:-100}
+			procd_close_instance
+			echo "EZ-WifiBroadcast: Telemetry TX Mode, Starting Telemetry..."
+			echo "EZ-WifiBroadcast: Telemetry Enabled on $(uci get wbc.telemetry.uart)."
+		fi
+	fi
+	
+	# 3. Uplink RX Instance
+	if [ $(uci get wbc.uplink.uplink_enable) -eq 1 ]; then
+		echo "EZ-WifiBroadcast: Uplink Enabled."
+		# air -> wbc.uplink.uart 
+		if [ "$(uci get wbc.uplink.mode)" = "rx" ]; then
+			procd_open_instance "wbc_rx_rc_telemetry"
+			procd_set_param stdout 1
+			procd_set_param stderr 1
+			procd_set_param command /usr/sbin/rx_rc_telemetry \
+				-p $(uci get wbc.uplink.port) \
+				-r 99 \
+				-b $(uci get wbc.uplink.baud) \
+				-o 0 \
+				-s $(uci get wbc.uplink.uart) \
+				$(uci get wbc.nic.iface)
+			procd_set_param pidfile /var/run/wbc/rx_rc_telemetry.pid
+			procd_set_param respawn ${respawn_threshold:-86400} ${respawn_timeout:-1} ${respawn_retry:-100}
+			procd_close_instance
+			echo "EZ-WifiBroadcast: Uplink RX Mode, Starting rx_rc_telemetry..."
+			echo "EZ-WifiBroadcast: Uplink Output Enabled on $(uci get wbc.uplink.uart)."
+		fi
+
 		# Listen on UDP port -> air
-		if [ $(uci get wbc.uplink.enable) -eq 1 ]; then
-			echo "EZWifiBroadcast: Uplink TX enabled on $(uci get wbc.uplink.uart)."
+		if [ "$(uci get wbc.uplink.mode)" = "tx" ]; then
 			procd_open_instance "wbc_uplink_tx_telemetry"
 			procd_set_param stdout 1
 			procd_set_param stderr 1
@@ -216,13 +186,28 @@ start_service() {
 			procd_set_param pidfile /var/run/wbc/tx_telemetry_uplink.pid
 			procd_set_param respawn ${respawn_threshold:-86400} ${respawn_timeout:-1} ${respawn_retry:-100}
 			procd_close_instance
-			echo "EZWifiBroadcast: Starting Uplink..."
-		else
-			echo "EZWifiBroadcast: Uplink disabled."
+			echo "EZ-WifiBroadcast: Uplink TX Mode, Starting tx_telemetry..."
+			echo "EZ-WifiBroadcast: Uplink TX Data Input From localhost:$(uci get wbc.uplink.listen_port)."
 		fi
-		
-		# 4. RSSI RX Instance
-		if [ $(uci get wbc.rssi.enable) -eq 1 ]; then
+	fi
+	
+	# 4. RSSI TX/RX Instance
+	if [ $(uci get wbc.rssi.enable) -eq 1 ]; then
+		echo "EZ-WifiBroadcast: RSSI Enabled."
+		# RSSI TX Instance
+		if [ "$(uci get wbc.rssi.mode)" = "tx" ]; then
+			procd_open_instance "wbc_rssitx"
+			procd_set_param stdout 1
+			procd_set_param stderr 1
+			procd_set_param command /usr/sbin/rssitx
+			procd_append_param command $(uci get wbc.nic.iface)
+			procd_set_param pidfile /var/run/wbc/rssitx.pid
+			procd_set_param respawn ${respawn_threshold:-86400} ${respawn_timeout:-1} ${respawn_retry:-100}
+			procd_close_instance
+			echo "EZ-WifiBroadcast: RSSI TX Mode, Starting rssitx..."
+		fi
+		# RSSI RX Instance
+		if [ "$(uci get wbc.rssi.mode)" = "rx" ]; then
 			procd_open_instance "wbc_rssirx"
 			procd_set_param stdout 1
 			procd_set_param stderr 1
@@ -231,12 +216,9 @@ start_service() {
 			procd_set_param pidfile /var/run/wbc/rssirx.pid
 			procd_set_param respawn ${respawn_threshold:-86400} ${respawn_timeout:-1} ${respawn_retry:-100}
 			procd_close_instance
-			echo "EZWifiBroadcast: Starting rssirx..."
-		else
-			echo "EZWifiBroadcast: RSSI RX Disabled."
+			echo "EZ-WifiBroadcast: RSSI RX Mode, Starting rssirx..."
 		fi
 	fi
-	
 }
 
 reload_service() {
